version: '2.2'
services:
  web:
    build: .
    command: yarn start
    depends_on:
      - mongo
    volumes:
      - .:/code
    ports:
      - "3000:3000"
  mongo:
    image: mongo
    restart: always
